# Settings
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-ghostty:RGB"
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

# Keymaps
set -g prefix C-Space
unbind C-b
bind-key C-Space send-prefix

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Window Navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Splits
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Appearance
set-option -g status-position top
set-option -g status-justify absolute-centre
set-option -g status-style "bg=default,fg=color7"

set -g pane-border-style "fg=color8"
set -g pane-active-border-style "fg=color4"
set -g message-style "fg=color4,bg=default"

set-window-option -g window-status-separator " • "
set-option -g window-status-style "bg=default,fg=color8"

# SSH and Standard Format
set-option -g window-status-format "#{?#{==:#{pane_current_command},ssh},󰌘 #(host=\$(echo '#{pane_title}' | sed 's/^ssh //; s/ .*//; s/.*@//; s/:.*//'); if echo \"\$host\" | grep -qE '^[0-9.]+\$|^[0-9]'; then echo '#W'; else echo \"\$host\"; fi | cut -c1-20),#W}"
set-option -g window-status-current-format "#[fg=color15,bold]#{?#{==:#{pane_current_command},ssh},󰌘 #(host=\$(echo '#{pane_title}' | sed 's/^ssh //; s/ .*//; s/.*@//; s/:.*//'); if echo \"\$host\" | grep -qE '^[0-9.]+\$|^[0-9]'; then echo '#W'; else echo \"\$host\"; fi | cut -c1-20),#W}#[fg=color4]#{?window_zoomed_flag, 󰊓,}"

# Left Status
set-option -g status-left-length 50
set-option -g status-left "#[bg=default,fg=color8]#{?client_prefix,, #S }#[bg=color4,fg=color0,bold]#{?client_prefix, #S ,}#[bg=default,fg=color8]"

# Right Status
set-option -g status-right ""

# Alert and Activity
set-option -g window-status-bell-style "bg=color4,fg=color0,bold"
set-option -g window-status-activity-style "bg=color15,fg=color0"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# run '~/.config/tmux/plugins/tpm/tpm'
