[mgr]
linemode    = "size"
show_hidden = true
sort_by     = "natural"
# mouse_events = []

[preview]
wrap       = "yes"
max_width  = 1500
max_height = 1500

[opener]
edit = [
	{ run = "${EDITOR:=nvim} %s", desc = "$EDITOR", block = true },
	{ run = "code %s", orphan = true },
]

[open]
prepend_rules = [
	{ url = "*.{ass,srt,ssa,sty,sup,vtt}", use = [ "subtitle", "edit", "reveal" ] },
]

[tasks]
image_alloc = 0
image_bound = [ 0, 0 ]
